{
    'name': " asset_management",
    'summary': "Asset Management",
    'sequence':15,
    'author': "Ebenezeri",
    'category': 'Uncategorized',
    'version': '0.1',
    'depends': ['base', 'web', 'mail', 'sale', 'board'],
    'data': [
        'security/ir.model.access.csv',
        'data/asset_template.xml',
        'data/asset_sequence.xml',
        'views/asset_management_view.xml',
        'views/asset_move_view.xml',
        'views/asset_dashboard_view.xml',
    ],
    "application": True,
    'installable': True,
     'license': 'AGPL-3',
}
